config/routes.rb
Rails.application.routes.draw do
  get 'perfil', to: "users#edit"
  resources :categories

  devise_for :users
  #get 'home/index'

  root to: 'home#index'

  resources :users, only: [:update]


  #get "notebooks", to: "notebooks#index"

 #get "notebooks/user/:user_id", to: 'notebooks#from_owner'

 resources :tasks do
  get "user/:user_id", to: "tasks#from_owner", on: :collection, as: :my_tasks
 end

 #es un objeto que podemos CRUD
 resources :notebooks do
  #ruta de coleccione para conjunto de objetos y member para un objeto en espesifico
  get "user/:user_id", to: "notebooks#from_owner", on: :collection, as: :my_notebooks
  
 end


  #get 'notebooks/new', to: 'notebooks#new', as: :new_notebook
  #GET consultar mediante el id retorna un registro
  #get 'notebooks/:id', to: 'notebooks#show', as: :show_notebook
  #GET consultar mediante id retorna registro vista 
  #get 'notebooks/:id/edit', to: 'notebooks#edit', as: :edit_notebook
  #PATCH actualizacion mediante lo suministrado en edit
  #patch '/notebooks/:id', to: 'notebooks#update', as: :notebook
  #PUT#POST Crear registro guarda de forma segura
  #post 'notebooks', to: 'notebooks#create'
  #DELETE eliminar recursos del back
  #delete '/notebooks/:id', to: 'notebooks#destroy'


  
   
  #put '/notebooks/:id', to: 'notebooks#update', as :notebook
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/notebook.rb
class Notebook < ApplicationRecord
    has_rich_text :content
    belongs_to :user #Campo adiciomal un cuaderno le pertenece a un usuario
    #has_many :tasks
    
end

app/controllers/notebooks_controller.rb
class NotebooksController < ApplicationController
    #before_action = todos los metodos que deben ser ejecutados antes de cualquier otro de esta clase 
    #after_action = todos los metodos que deben ser ejecutados despues de cualquier otro de esta clase 
    #CRUD = CREAR, LEER, ACTUALIZAR Y ELIMINAR
    #llamamos el mtodo y con only indicamos en cuales aplicara las que no esten no seran tomadas en cuenta
    before_action :find_notebook, except: [:new, :create, :index, :from_owner, :notebook_params]
    before_action :authenticate_user!, only: [:create, :edit, :new, :update, :show, :destory]
    #before_action :find_notebook, except: [:new,:create]


    def from_owner
        @user = User.find(params[:user_id])
        

    end

    def index 
        #todos los objetos, cuadernos
        @notebooks = Notebook.all
    end

    def find_notebook
        @notebook = Notebook.find(params[:id])
    end

    #Carga el registro segun el ID que se recibe por get declarado en routes
    def show
        #@notebook = Notebook.find(params[:id])
    end

    #Carga el registro segun el ID que se recibe por get declarado en routes
    def edit
        #@notebook = Notebook.find(params[:id])
    end

    #Metodo de la clase que recibe por parametros las columnas del registro con ayuda de params
    def create
        #Por comvencion puede ser llamado el objeto notebook para crear uno nuevo
        #@notebook = current_user.notebooks.create(title: params[:notebook][:title], description: params[:notebook][:description], content: params[:notebook][:content])
        #Parametros en general del objeto hash completo
        @notebook = current_user.notebooks.create(notebook_params)
        
        #redirecciona despues de la ejecucion
        redirect_to @notebook
    end

    #Metodo del objeto que recibe por parametroslos las columnas del registro con ayuda de params
    def update
        #@notebook = Notebook.find(params[:id])
        #@notebook.update(title: params[:notebook][:title], description: params[:notebook][:description], content: params[:notebook][:content])
        @notebook.update(notebook_params )
        redirect_to @notebook

    end

    #Carga el registro a partir de la solicitud de la url del id
    def destroy
        @notebook = Notebook.find(params[:id])
        @notebook.destroy
        redirect_to root_path
    end

    #Metodo de la clase para la generacion de nuevo objeto
    def new
        @notebook = Notebook.new
    end
    
    #parametros fuertes restringir injeccion sql
    def notebook_params
        params.require(:notebook).permit(:title,:description,:content)
    end
    
    
end

app/helpers/notebooks_helper.rb
module NotebooksHelper
end

app/views/notebooks/_form.html.erb
<%#vistas parciales que son llamadas desde el render de la vista padre edit,create 
<%#Vinculacion de un formulario a un objeto de modelo  %>
<%=form_with(model: @notebook, local:true) do |form| %>
    <br>
    <div class="container-sm border border-info rounded-3">
        <br>
        <div class="text-center">
            <%= form.label "Nombre del Cuaderno:", { class: "form-label"} %>
            <%= form.text_field :title%>
        </div>
        <br>
        <div class="">
            <%= form.label "Descripcion"%>
            <%= form.text_area :description, { class: "form-control", placeholder: "Breve descripcion del contenido" }%>
        </div>
        <br>
        <div class="">
            <%= form.label :content%>
            <%# %>
            <%# complemento de text, rails action_text:install%>
            <%= form.rich_text_area :content%>
        </div>  
        <br>

    </div>
    <br>
    <div class="container-sm">
        <%# accion botton %>
        <%= form.submit "Crear Categoria", class:"btn btn-primary"%>
    </div>
<% end %>

app/views/notebooks/_notebook.html.erb
<%#vistas parciales que son llamadas desde el render de la vista padre index
entiende que es el conjunto de objetos y los recorre para mostrar
el archivo debe llamarce igual que el modelo en minuscula%>
<div class="row">
  <div class="col-sm-6">
  <br>
    <div class="card mb-3 border border-info rounded-3">
      <div class="card-body">
        <h5 class="card-title"><%=notebook.id%>) <%=notebook.title%></h5>
        <p class="card-text"><%=notebook.description%></p>
        <p class="card-text"><%= notebook.created_at%></p>
        <%= link_to "ver mas", notebook%>
        <br>
      </div>
    </div>
  </div>
</div>

app/views/notebooks/edit.html.erb
<div class= "small-container center-block">
    <%= render 'notebooks/form' %>
</div>

app/views/notebooks/from_owner.html.erb
<div class="container-sm">
    <br>
    <h1>Cuadernos del usuario: <%= @user.email%></h1>

    <%#En ves de pasar la vista parcial pasamos el objeto del metodo en el controlador%>
    <%= render @user.notebooks%>
</div>

app/views/notebooks/index.html.erb
<div class="container-sm">
    <br>
    <h3>Mis cuadernos</h3>

<%#En ves de pasar la vista parcial pasamos el objeto del metodo en el controlador%>
    <%= render @notebooks%>
</div>

<%#<% @notebooks.each do |notebook| %
<%#    <div class="card" style="padding:15px;max-width:300px;margin-top:1em">
 <%#       < class="text-uppercase"><%=notebook.title%>
<%#        < class=""><%=notebook.description%>
<%#        < class="text-secondary"><%= notebook.created_at%>
<%#        <%= link_to "ver mas", notebook%>
<%#    </div>   
<%end%>

app/views/notebooks/new.html.erb
<%= render 'notebooks/form' %>

app/views/notebooks/show.html.erb
<%#Apartir de la instancia traer los registros de cada columna%>
<br>
<div class="card text-center container-sm">
    <h4>Cuaderno</h4>
  <div class="card-header">
    <h5>Creado por: <strong><%= @notebook.user.email%></strong></h5>
  </div>
  <div class="card-body">
    <h3 class="card-title"><%= @notebook.title%></h3>
    <p class="card-text"><%= @notebook.description%></p>
    <p class="card-text"><%= @notebook.content%></p>
    
    <a><%= button_to "Editar", edit_notebook_path, class:"btn btn-outline-warning" %></a>
    <%= link_to 'Editar', edit_notebook_path%>
    <br>
    <a><%= button_to "Eliminar", @notebook, method: :delete,class:"btn btn-outline-danger" %></a>
    
  </div>
  <div class="card-footer text-muted">
    <%= @notebook.created_at%>
  </div>
</div>