config/routes.rb
Rails.application.routes.draw do
  get 'perfil', to: "users#edit"
  resources :categories

  devise_for :users
  #get 'home/index'

  root to: 'home#index'

  resources :users, only: [:update]


  #get "notebooks", to: "notebooks#index"

 #get "notebooks/user/:user_id", to: 'notebooks#from_owner'

 resources :tasks do
  get "user/:user_id", to: "tasks#from_owner", on: :collection, as: :my_tasks
 end

 #es un objeto que podemos CRUD
 resources :notebooks do
  #ruta de coleccione para conjunto de objetos y member para un objeto en espesifico
  get "user/:user_id", to: "notebooks#from_owner", on: :collection, as: :my_notebooks
  
 end


  #get 'notebooks/new', to: 'notebooks#new', as: :new_notebook
  #GET consultar mediante el id retorna un registro
  #get 'notebooks/:id', to: 'notebooks#show', as: :show_notebook
  #GET consultar mediante id retorna registro vista 
  #get 'notebooks/:id/edit', to: 'notebooks#edit', as: :edit_notebook
  #PATCH actualizacion mediante lo suministrado en edit
  #patch '/notebooks/:id', to: 'notebooks#update', as: :notebook
  #PUT#POST Crear registro guarda de forma segura
  #post 'notebooks', to: 'notebooks#create'
  #DELETE eliminar recursos del back
  #delete '/notebooks/:id', to: 'notebooks#destroy'


  
   
  #put '/notebooks/:id', to: 'notebooks#update', as :notebook
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/partials/_nav.html.erb
<nav class="nav bg-light">
    <li class="nav-item">
        <%= link_to "Inicio", root_path, class:"nav-link"%>
    </li>
    <li class="nav-item">
        
    </li>
    <li class="nav-item">
        
    </li>
    <li class="nav-item">
       
    </li>


    <li class="nav-item">
        <%if user_signed_in?%>
            <%= link_to "Perfil", perfil_path, class:"nav-link"%>
        <%end%>
    </li>
    <%#<li class="nav-item">
        <%if user_signed_in?%>
    <%#        <%= link_to "Cuadernos", notebooks_path, class:"nav-link"%>
    <%# <%end%>
    <%#</li>%>
    <li class="nav-item">
        <%if user_signed_in?%>
            <%= link_to "Mis Cuadernos", "notebooks/user/#{current_user.id}", class:"nav-link"%>
        <%end%>
    </li>
    <li class="nav-item">
        <%if user_signed_in?%>
            <%= link_to "Nuevo Cuaderno", new_notebook_path, class:"nav-link"%>
        <%end%>
    </li>
    <li class="nav-item">
        <%if user_signed_in?%>
            <%= link_to "Mis Tareas", "tasks/user/#{current_user.id}", class:"nav-link"%>
        <%end%>
    </li>
    <li class="nav-item">
        <%if user_signed_in?%>
            <%= link_to "Tareas", tasks_path, class:"nav-link"%>
        <%end%>
    </li>
    <li class="nav-item">
        <%if user_signed_in?%>
            <%= link_to "Nueva Tarea", new_task_path, class:"nav-link"%>
        <%end%>
    </li>
    <li class="nav-item">
        <%if user_signed_in?%>
             <%= link_to "Categorias", categories_path, class:"nav-link"%>
        <%end%>
    </li>

    
</nav>